{% set name = "yachalk" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yachalk-{{ version }}.tar.gz
  sha256: 4f2ac54adef924fda03756a94c8b4b780bf8aecf80bbd6afa80e9f74d6cecc5f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - importlib-resources
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - yachalk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bluenote10/yachalk
  summary: Terminal string styling done right
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
