{% set name = "yachalk" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yachalk-{{ version }}.tar.gz
  sha256: ee917e41c127a2302526aa169c6032f1505fab5a1045bd7a0c320b0194e8d992

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - wheel
  run:
    - importlib-resources
    - python >=3.7
    - setuptools

test:
  imports:
    - yachalk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluenote10/yachalk
  summary: Terminal string styling done right
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
